[general]
charge_radius=0.5 #mm
start_offset=0 #mm
gap=0 #mm
inverse_permittivity=3 #[/C]

[[patterns.lines]]
quantity=1.0
start={x=0,y=50}
end={x=200,y=50}
[[patterns.lines]]
quantity=-1.0
start={x=0,y=100}
end={x=200,y=100}
